FROM node:alpine AS builder
ENV NODE_ENV production
WORKDIR /app
COPY ./package.json /app
RUN npm install
COPY . .
CMD ["npm", "run build"]

FROM nginx:1.21.0-alpine as production
ENV NODE_ENV production
COPY --from=builder /app/build /usr/share/nginx/html
# Add your nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Expose port
EXPOSE 80
# Start nginx
CMD ["nginx", "-g", "daemon off;"]